#pragma once

// The single instruction list used to declare, define, register and validate
// dedicated assembler callbacks. The mnemonic is stringized at expansion sites.
// clang-format off
#define ASSEMBLER_INSTRUCTIONS(Instruction) \
  Instruction(adc, Adc)                    \
  Instruction(add, Add)                    \
  Instruction(and, And)                    \
  Instruction(bswap, Bswap)                \
  Instruction(call, Call)                  \
  Instruction(cdq, Cdq)                    \
  Instruction(clc, Clc)                    \
  Instruction(cld, Cld)                    \
  Instruction(cli, Cli)                    \
  Instruction(cmc, Cmc)                    \
  Instruction(cmp, Cmp)                    \
  Instruction(cpuid, Cpuid)                \
  Instruction(cqo, Cqo)                    \
  Instruction(dec, Dec)                    \
  Instruction(div, Div)                    \
  Instruction(hlt, Hlt)                    \
  Instruction(imul, Imul)                  \
  Instruction(idiv, Idiv)                  \
  Instruction(inc, Inc)                    \
  Instruction(int, Int)                    \
  Instruction(int3, Int3)                  \
  Instruction(ja, Ja)                      \
  Instruction(jae, Jae)                    \
  Instruction(jb, Jb)                      \
  Instruction(jbe, Jbe)                    \
  Instruction(jc, Jc)                      \
  Instruction(je, Je)                      \
  Instruction(jg, Jg)                      \
  Instruction(jge, Jge)                    \
  Instruction(jl, Jl)                      \
  Instruction(jle, Jle)                    \
  Instruction(jmp, Jmp)                    \
  Instruction(jna, Jna)                    \
  Instruction(jnae, Jnae)                  \
  Instruction(jnb, Jnb)                    \
  Instruction(jnbe, Jnbe)                  \
  Instruction(jnc, Jnc)                    \
  Instruction(jne, Jne)                    \
  Instruction(jng, Jng)                    \
  Instruction(jnge, Jnge)                  \
  Instruction(jnl, Jnl)                    \
  Instruction(jnle, Jnle)                  \
  Instruction(jno, Jno)                    \
  Instruction(jnp, Jnp)                    \
  Instruction(jns, Jns)                    \
  Instruction(jnz, Jnz)                    \
  Instruction(jo, Jo)                      \
  Instruction(jp, Jp)                      \
  Instruction(jpe, Jpe)                    \
  Instruction(jpo, Jpo)                    \
  Instruction(js, Js)                      \
  Instruction(jz, Jz)                      \
  Instruction(lea, Lea)                    \
  Instruction(leave, Leave)                \
  Instruction(mov, Mov)                    \
  Instruction(movsx, Movsx)                \
  Instruction(movsxd, Movsxd)              \
  Instruction(movzx, Movzx)                \
  Instruction(mul, Mul)                    \
  Instruction(neg, Neg)                    \
  Instruction(nop, Nop)                    \
  Instruction(not, Not)                    \
  Instruction(or, Or)                      \
  Instruction(pop, Pop)                    \
  Instruction(push, Push)                  \
  Instruction(pushfq, Pushfq)              \
  Instruction(popfq, Popfq)                \
  Instruction(rdtsc, Rdtsc)                \
  Instruction(ret, Ret)                    \
  Instruction(rol, Rol)                    \
  Instruction(ror, Ror)                    \
  Instruction(sal, Sal)                    \
  Instruction(sar, Sar)                    \
  Instruction(sbb, Sbb)                    \
  Instruction(shl, Shl)                    \
  Instruction(shr, Shr)                    \
  Instruction(sub, Sub)                    \
  Instruction(stc, Stc)                    \
  Instruction(std, Std)                    \
  Instruction(sti, Sti)                    \
  Instruction(syscall, Syscall)            \
  Instruction(test, Test)                  \
  Instruction(ud2, Ud2)                    \
  Instruction(xchg, Xchg)                  \
  Instruction(xor, Xor)
// clang-format on
