// Define variables (this is a comment)
let name = "John"
let age = 30

// Display a greeting
echo("Hello, my name is {name}")

// Perform conditional checks
if age < 18 {
    echo("I'm not an adult yet")
} else {
    echo("I'm an adult")
}

// Loop through an array
let fruits = [
    "apple", 
    "banana", // Comments are supported inside array literals!
    "cherry", 
    "date",
]

echo("My favorite fruits are:")
for fruit in fruits {
    echo(fruit)
}
