include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/LLVMDistribution.cmake")

function(recurloop_validate_llvm_archive root out_found)
    set(config "${root}/lib/cmake/llvm/LLVMConfig.cmake")
    set(llvm_config "${root}/bin/llvm-config")
    if(WIN32)
        set(llvm_config "${root}/bin/llvm-config.exe")
    endif()
    if(NOT EXISTS "${config}" OR NOT EXISTS "${llvm_config}")
        set(${out_found} FALSE PARENT_SCOPE)
        return()
    endif()
    execute_process(COMMAND "${llvm_config}" --version
        OUTPUT_VARIABLE version OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE result ERROR_QUIET TIMEOUT 30)
    if(NOT result EQUAL 0 OR NOT version STREQUAL RECURLOOP_LLVM_VERSION)
        set(${out_found} FALSE PARENT_SCOPE)
        return()
    endif()
    set(${out_found} TRUE PARENT_SCOPE)
endfunction()

function(recurloop_prepare_llvm_archive out_root)
    if(NOT DEFINED RECURLOOP_DEPS_DIR OR RECURLOOP_DEPS_DIR STREQUAL "")
        message(FATAL_ERROR "RECURLOOP_DEPS_DIR must be set before preparing LLVM")
    endif()

    recurloop_llvm_archive_metadata(url sha platform_id filename)
    set(root "${RECURLOOP_DEPS_DIR}/llvm/${RECURLOOP_LLVM_VERSION}/${platform_id}")
    set(manifest "${root}/.recurloop-archive")
    set(expected_manifest "URL=${url}\nSHA256=${sha}\nLLVM=${RECURLOOP_LLVM_VERSION}\n")

    recurloop_validate_llvm_archive("${root}" valid)
    if(valid AND EXISTS "${manifest}")
        file(READ "${manifest}" actual_manifest)
        if(actual_manifest STREQUAL expected_manifest)
            set(${out_root} "${root}" PARENT_SCOPE)
            return()
        endif()
    endif()

    file(MAKE_DIRECTORY "${RECURLOOP_DEPS_DIR}" "${RECURLOOP_DEPS_DIR}/downloads")
    file(LOCK "${RECURLOOP_DEPS_DIR}/llvm-archive.lock" GUARD FUNCTION TIMEOUT 120 RESULT_VARIABLE lock_result)
    if(NOT lock_result EQUAL 0)
        message(FATAL_ERROR
            "Another process is preparing LLVM in ${RECURLOOP_DEPS_DIR}; archive lock timeout reached")
    endif()

    recurloop_validate_llvm_archive("${root}" valid)
    if(valid AND EXISTS "${manifest}")
        file(READ "${manifest}" actual_manifest)
        if(actual_manifest STREQUAL expected_manifest)
            set(${out_root} "${root}" PARENT_SCOPE)
            return()
        endif()
    endif()

    set(archive "${RECURLOOP_DEPS_DIR}/downloads/${filename}")
    set(download TRUE)
    if(EXISTS "${archive}")
        file(SHA256 "${archive}" existing_sha)
        if(existing_sha STREQUAL sha)
            set(download FALSE)
        else()
            message(STATUS "Discarding LLVM archive with wrong checksum: ${archive}")
            file(REMOVE "${archive}")
        endif()
    endif()

    if(download)
        message(STATUS "Downloading official LLVM ${RECURLOOP_LLVM_VERSION}: ${filename}")
        file(DOWNLOAD "${url}" "${archive}"
            EXPECTED_HASH "SHA256=${sha}"
            TLS_VERIFY ON SHOW_PROGRESS
            STATUS status TIMEOUT 7200 INACTIVITY_TIMEOUT 120)
        list(GET status 0 status_code)
        list(GET status 1 status_message)
        if(NOT status_code EQUAL 0)
            file(REMOVE "${archive}")
            message(FATAL_ERROR "LLVM archive download failed: ${status_message}")
        endif()
    endif()

    set(extract "${root}.extracting")
    file(REMOVE_RECURSE "${extract}" "${root}")
    file(MAKE_DIRECTORY "${extract}")
    message(STATUS "Extracting LLVM ${RECURLOOP_LLVM_VERSION} to ${root}")
    file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${extract}")

    set(candidate "")
    if(EXISTS "${extract}/lib/cmake/llvm/LLVMConfig.cmake")
        set(candidate "${extract}")
    else()
        file(GLOB children LIST_DIRECTORIES TRUE "${extract}/*")
        foreach(child IN LISTS children)
            if(IS_DIRECTORY "${child}" AND EXISTS "${child}/lib/cmake/llvm/LLVMConfig.cmake")
                if(NOT candidate STREQUAL "")
                    file(REMOVE_RECURSE "${extract}")
                    message(FATAL_ERROR "LLVM archive contains more than one SDK root")
                endif()
                set(candidate "${child}")
            endif()
        endforeach()
    endif()
    if(candidate STREQUAL "")
        file(REMOVE_RECURSE "${extract}")
        message(FATAL_ERROR "LLVM archive does not contain lib/cmake/llvm/LLVMConfig.cmake")
    endif()

    get_filename_component(root_parent "${root}" DIRECTORY)
    file(MAKE_DIRECTORY "${root_parent}")
    if(candidate STREQUAL extract)
        file(RENAME "${extract}" "${root}")
    else()
        file(RENAME "${candidate}" "${root}")
        file(REMOVE_RECURSE "${extract}")
    endif()
    file(WRITE "${manifest}" "${expected_manifest}")

    recurloop_validate_llvm_archive("${root}" valid)
    if(NOT valid)
        file(REMOVE_RECURSE "${root}")
        message(FATAL_ERROR
            "Extracted LLVM archive cannot run on this host or has the wrong version. "
            "For musl/custom hosts use RECURLOOP_LLVM_PROVIDER=SYSTEM.")
    endif()
    set(${out_root} "${root}" PARENT_SCOPE)
endfunction()
