include_guard(GLOBAL)

set(RECURLOOP_PACKAGE_LIBRARIES
    language-kit shell inferred http gui ide project embed)

function(recurloop_require_package_layout prefix)
    set(required_files
        "bin/recurloop"
        "share/recurloop/BUILD-COMPATIBILITY.txt"
        "share/recurloop/RELEASE-METADATA.txt")
    foreach(library IN LISTS RECURLOOP_PACKAGE_LIBRARIES)
        list(APPEND required_files "share/recurloop/libraries/${library}.rli")
    endforeach()
    foreach(relative IN LISTS required_files)
        if(NOT EXISTS "${prefix}/${relative}" OR IS_DIRECTORY "${prefix}/${relative}")
            message(FATAL_ERROR "Installed package is incomplete: missing ${relative}")
        endif()
        file(SIZE "${prefix}/${relative}" size)
        if(size EQUAL 0)
            message(FATAL_ERROR "Installed package is incomplete: empty ${relative}")
        endif()
    endforeach()
endfunction()

function(recurloop_package_manifest_content prefix out_content)
    file(GLOB_RECURSE package_files RELATIVE "${prefix}" LIST_DIRECTORIES FALSE "${prefix}/*")
    list(SORT package_files)
    set(content "")
    foreach(relative IN LISTS package_files)
        if(relative STREQUAL "share/recurloop/PACKAGE-MANIFEST.sha256")
            continue()
        endif()
        if(relative MATCHES "(^|/)\\.smoke(/|$)")
            continue()
        endif()
        file(SHA256 "${prefix}/${relative}" digest)
        string(APPEND content "${digest}  ${relative}\n")
    endforeach()
    set(${out_content} "${content}" PARENT_SCOPE)
endfunction()

function(recurloop_write_package_manifest prefix)
    recurloop_package_manifest_content("${prefix}" content)
    file(MAKE_DIRECTORY "${prefix}/share/recurloop")
    file(WRITE "${prefix}/share/recurloop/PACKAGE-MANIFEST.sha256" "${content}")
endfunction()

function(recurloop_verify_package_manifest prefix)
    set(manifest "${prefix}/share/recurloop/PACKAGE-MANIFEST.sha256")
    if(NOT EXISTS "${manifest}")
        message(FATAL_ERROR "Installed package has no integrity manifest: ${manifest}")
    endif()
    file(READ "${manifest}" expected)
    recurloop_package_manifest_content("${prefix}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Installed package integrity manifest does not match its contents")
    endif()
endfunction()
