cmake_minimum_required(VERSION 3.25)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED RECURLOOP_DEPS_DIR OR RECURLOOP_DEPS_DIR STREQUAL "")
    set(RECURLOOP_DEPS_DIR "${ROOT}/.cache/deps")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/LLVMArchive.cmake")
recurloop_prepare_llvm_archive(llvm_root)
if(DEFINED OUTPUT_FILE AND NOT OUTPUT_FILE STREQUAL "")
    file(WRITE "${OUTPUT_FILE}" "${llvm_root}\n")
endif()
message(STATUS "Official LLVM ${RECURLOOP_LLVM_VERSION} ready: ${llvm_root}")
